[features]
seeds = false
[programs.devnet]
nft_id = "3mAW7AVHr7TRvYkmeXKdTsDCYjdnJ2t4TpFeXPb57BRu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
